query ListFacilitySections @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  facilitySections {
    id
    facilityId
    name
    sport
    description
    isBooked
    createdAt
  }
}
