query SearchFacilitySectionsByName($name: String!) @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  facilitySections(where: { name: { eq: $name } }) {
    id
    facilityId
    name
    sport
    description
    isBooked
    createdAt
  }
}
