type User @table(name: "users") {
  id: UUID!
  email: String
  name: String
  createdAt: Timestamp
}

type Facility @table(name: "facilities") {
  id: UUID!
  name: String
  address: String
  description: String
  openingHours: String
  contactNumber: String
  imageUrl: String
  createdAt: Timestamp
}

type FacilitySection @table(name: "facility_sections") {
  id: UUID!
  facilityId: UUID
  name: String
  sport: String
  description: String
  createdAt: Timestamp
}

type Booking @table(name: "bookings") {
  id: UUID!
  status: String
  bookingTime: Timestamp
  userId: UUID
  sectionId: UUID
  createdAt: Timestamp
}
